apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-secrets-updater
  namespace: ecr-secrets-updater
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ecr-secrets-updater
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ecr-secrets-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ecr-secrets-updater
subjects:
  - kind: ServiceAccount
    name: ecr-secrets-updater
    namespace: ecr-secrets-updater
